### ISSUE TITLE
Set Analytics Goal: User clicks Join Meetup button

### ISSUE THREAD

**Issue by viperior** [TylerWebDev/TylerWebDev.github.io#4]

**Comment by LookLittleJohn** [comment]
+1
I'd like to see how goals work in Google Analytics.

**Comment by loganhenson** [comment]
Blog post!

**Comment by LookLittleJohn** [comment]
8a81371

I think I made this work... I'm waiting to get results in Google Analytics right now.

**Comment by loganhenson** [comment]
@LookLittleJohn did you do this or ?

**Comment by LookLittleJohn** [comment]
I thought I did it but I guess I did out wrong.. The hit counter has never gone up

**Comment by loganhenson** [comment]
no one is picking this up, closing for now
