### ISSUE TITLE
Define social media interaction goals

### ISSUE THREAD

**Issue by viperior** [TylerWebDev/TylerWebDev.github.io#5]
Identify and define what type of goals we should set regarding user interaction with our social media accounts.

**Comment by loganhenson** [comment]
I am not sure how to approach this one, do you mean something like: number of likes, number of retweets?

**Comment by viperior** [comment]
This issue is for social media interaction on the website itself. Here are some example goals:

- User Likes page using Facebook Like button. (Like button widget on page)
- User follows Twitter account using on-page Twitter Follow button.
- User (takes some positive action) using (some other social media account button).

**Comment by viperior** [comment]
These actions would be tracked as goals within Google Analytics.

**Comment by loganhenson** [comment]
any update @viperior

**Comment by loganhenson** [comment]
condensing
