### ISSUE TITLE
Define first-time visitor goals

### ISSUE THREAD

**Issue by viperior** [TylerWebDev/TylerWebDev.github.io#6]
Identify and define goal(s) for "successful" first-time visit to the site. Define what is considered a successful response, in terms of user behavior, to a user's initial experience on the site.

This could include one or more of these criteria:
- number of pages visited,
- amount of time spent,
- fulfillment of other goals (such as clicking "join this meetup button"),
- and so forth.

**Comment by loganhenson** [comment]
I would be interested in:

1. where they are coming from (google? direct url?)
2. amount of clicks on join this meetup button (if it is getting used, and not fulfilling new members, how can we make that process smoother)

**Comment by loganhenson** [comment]
condensing to more general goal
