### ISSUE TITLE
Map is affecting UX on mobile when scrolling down the page.

### ISSUE THREAD

**Issue by joseph-walker** [TylerWebDev/TylerWebDev.github.io#7]
* scroll scroll scroll drag-map
Disable map-drag for touch

**Comment by LookLittleJohn** [comment]
I can fix this one over lunch! I need the contributions ;P

**Comment by loganhenson** [comment]
@LookLittleJohn Have a chance to look at this yet?

**Comment by LookLittleJohn** [comment]
Nah, it's a simple fix,c though. You need to disable the map attribute 'isdraggable' when a mobile device is detected. What I'm not sure on is what to make the assumption of a mobile device on. Should I check the viewport size or check to see if there if the screentouch event is there? Or is there a better way to make that judgment call?

**Comment by joseph-walker** [comment]
Instead, I would add an overlay on top of the map that gets disabled if you double tap it. That way mobile users who want to move the map around can, but not until they opt into it.

**Comment by LookLittleJohn** [comment]
![agreed](http://s3.amazonaws.com/rapgenius/ryan-point-agree-the-office.gif)

**Comment by loganhenson** [comment]
fixed in non-profits-form branch
