### ISSUE TITLE
Mobile Truncates on Safari 

### ISSUE THREAD

**Issue by theshockalino** [TylerWebDev/TylerWebDev.github.io#8]
![img_1513](https://cloud.githubusercontent.com/assets/9598879/10299956/120bc3b6-6bb6-11e5-9d70-6a1a24882b6a.PNG)

**Comment by loganhenson** [comment]
Joseph and I looked into this, it is the z-index on the :before/:after circles giving the oval shape to the nav items. For some reason on safari it is pushing them to the top and blocking the li content.

**Comment by joseph-walker** [comment]
Resolved on Safari. Stacking contexts weren't calculating the same way - because who needs standards, right?
