### ISSUE TITLE
Look into inlining SVG elements in Jekyll build as opposed to through client-side scripts

### ISSUE THREAD

**Issue by joseph-walker** [TylerWebDev/TylerWebDev.github.io#9]
The client-side inlining works, but causes a brief [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content). It's being handled by /js/lib/svg-injector.min.js

**Comment by loganhenson** [comment]
Ill likely handle this with a gulp task, having us work in a ```.index.html``` and it get transformed into ```index.html``` on talk run. @joseph-walker tell me what you think

**Comment by joseph-walker** [comment]
Sure that's fine. Whatever works so long as it's documented for future development.

**Comment by loganhenson** [comment]
not going to bother with this right now
